spring:
  profiles:
    active: "dev"
---
spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: aop
  jpa:
    hibernate:
      ddl-auto: validate
#          ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show-sql: true
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/aop
    username: aop
    password: aop
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog.xml
server:
  port: 8080
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs